base:
  project: spam-message-classifier
  random_state: 42
  target_col: label

data_source:
  batch_files: Dataset/spam_or_not_spam.csv


load_data:
  raw_dataset_csv: data/raw/spam_or_not_spam.csv

split_data:
  train_path: data/processed/train_spam_or_not_spam.csv
  test_path: data/processed/test_spam_or_not_spam.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib