base:
  project: spam-message-classifier
  random_state: 42
  target_col: label
  main_col: email

data_source:
  batch_files: Dataset/spam_or_not_spam.csv


load_data:
  raw_dataset_csv: data/raw/spam_or_not_spam.csv
  x_csv: data/raw/x_array.csv.npy
  y_csv: data/raw/y_array.csv.npy

dl_params:
  voc_size: 5000
  sent_length: 200
  padding: pre
  embedding_vector_features: 40
  LSTM: 100
  loss: binary_crossentropy
  optimizer: adam
  metrics: accuracy
  activation: sigmoid
  epochs: 10
  batch_size: 64

split_data:
  x_train_path: data/processed/x_train_spam_or_not_spam.csv.npy
  x_test_path: data/processed/x_test_spam_or_not_spam.csv.npy
  y_train_path: data/processed/y_train_spam_or_not_spam.csv.npy
  y_test_path: data/processed/y_test_spam_or_not_spam.csv.npy
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib